spring:
  profiles:
    active: dev
  datasource:

      data-source-class-name:  com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/dbstronger?characterEncoding=utf8&useSSL=true
      username: root
      password: 123456
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true


